#include "pages.h"

static const char PAGE_MAIN_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>TapGate Portal</title>\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #0D1520;\n"
"            --text-color: #E6EEF8;\n"
"            --muted-color: #9CA3AF;\n"
"            --button-height: 52px;\n"
"        }\n"
"        * { box-sizing: border-box; }\n"
"        body {\n"
"            margin: 0;\n"
"            font-family: 'Segoe UI', Tahoma, sans-serif;\n"
"            background: var(--bg-color);\n"
"            color: var(--text-color);\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"        }\n"
"        .wrapper {\n"
"            width: min(440px, 92vw);\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 24px;\n"
"            padding: 32px 24px;\n"
"            text-align: center;\n"
"        }\n"
"        .logo {\n"
"            height: calc(var(--button-height) * 2);\n"
"            width: auto;\n"
"            align-self: center;\n"
"            filter: drop-shadow(0 6px 12px rgba(0, 0, 0, 0.25));\n"
"        }\n"
"        .buttons {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 16px;\n"
"        }\n"
"        button {\n"
"            height: var(--button-height);\n"
"            border-radius: 14px;\n"
"            border: none;\n"
"            background: linear-gradient(135deg, #0B2347 0%, #1F4F9E 52%, #47A5FF 100%);\n"
"            color: #FFFFFF;\n"
"            font-size: 17px;\n"
"            font-weight: 600;\n"
"            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.35);\n"
"            cursor: pointer;\n"
"            transition: all 0.15s ease;\n"
"        }\n"
"        button:focus, button:hover {\n"
"            background: linear-gradient(135deg, #133566 0%, #2F6AC6 52%, #63B7FF 100%);\n"
"        }\n"
"        button:active {\n"
"            background: linear-gradient(135deg, #081a35 0%, #183d78 52%, #3a7fc0 100%);\n"
"            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.35);\n"
"        }\n"
"        button:disabled {\n"
"            opacity: 0.55;\n"
"            cursor: not-allowed;\n"
"            box-shadow: none;\n"
"        }\n"
"        .version {\n"
"            font-size: 12px;\n"
"            color: var(--muted-color);\n"
"            letter-spacing: 0.4px;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <main class=\"wrapper\">\n"
"        <img src=\"/assets/logo.png\" alt=\"TapGate logo\" class=\"logo\">\n"
"        <div class=\"buttons\">\n"
"            <button type=\"button\" disabled>TapGate</button>\n"
"            <button type=\"button\" onclick=\"window.location.href='/api/v1/ap/';\">AP setting</button>\n"
"            <button type=\"button\" disabled>WiFi connection</button>\n"
"            <button type=\"button\" disabled>Clients</button>\n"
"            <button type=\"button\" disabled>Events</button>\n"
"        </div>\n"
"        <div class=\"version\">TapGate ver: 1</div>\n"
"    </main>\n"
"</body>\n"
"</html>\n";

const char *http_service_page_main_html(void)
{
    return PAGE_MAIN_HTML;
}
