#include "pages.h"

static const char PAGE_AP_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>TapGate AP Settings</title>\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #0D1520;\n"
"            --text-color: #E6EEF8;\n"
"            --label-color: #9CA3AF;\n"
"            --label-focus: #3B82F6;\n"
"            --input-bg: #0C1117;\n"
"            --input-border: #2A3642;\n"
"            --input-error: #F87171;\n"
"            --placeholder-color: rgba(122, 138, 159, 0.7);\n"
"            --button-height: 52px;\n"
"        }\n"
"        * { box-sizing: border-box; }\n"
"        body {\n"
"            margin: 0;\n"
"            font-family: 'Segoe UI', Tahoma, sans-serif;\n"
"            background: var(--bg-color);\n"
"            color: var(--text-color);\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"        }\n"
"        .container {\n"
"            width: min(420px, 92vw);\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 20px;\n"
"            padding: 24px;\n"
"        }\n"
"        h1 {\n"
"            font-size: 28px;\n"
"            margin: 0;\n"
"            text-align: center;\n"
"        }\n"
"        .form-field {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 8px;\n"
"        }\n"
"        label {\n"
"            font-size: 14px;\n"
"            color: var(--label-color);\n"
"            letter-spacing: 0.3px;\n"
"        }\n"
"        .form-field:focus-within label {\n"
"            color: var(--label-focus);\n"
"        }\n"
"        input {\n"
"            height: 48px;\n"
"            padding: 0 16px;\n"
"            border-radius: 12px;\n"
"            border: 1px solid var(--input-border);\n"
"            background: linear-gradient(180deg, #10161D 0%, #0C1117 100%);\n"
"            color: var(--text-color);\n"
"            font-size: 16px;\n"
"        }\n"
"        input::placeholder {\n"
"            color: var(--placeholder-color);\n"
"        }\n"
"        input:focus {\n"
"            outline: none;\n"
"            border-color: var(--label-focus);\n"
"            box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.25);\n"
"        }\n"
"        input.error {\n"
"            border-color: var(--input-error);\n"
"        }\n"
"        .actions {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 16px;\n"
"            margin-top: 12px;\n"
"        }\n"
"        button {\n"
"            height: var(--button-height);\n"
"            border-radius: 14px;\n"
"            border: none;\n"
"            background: linear-gradient(135deg, #0B2347 0%, #1F4F9E 52%, #47A5FF 100%);\n"
"            color: #FFFFFF;\n"
"            font-size: 17px;\n"
"            font-weight: 600;\n"
"            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.35);\n"
"            cursor: pointer;\n"
"            transition: all 0.15s ease;\n"
"        }\n"
"        button:focus, button:hover {\n"
"            background: linear-gradient(135deg, #133566 0%, #2F6AC6 52%, #63B7FF 100%);\n"
"        }\n"
"        button:active {\n"
"            background: linear-gradient(135deg, #081a35 0%, #183d78 52%, #3a7fc0 100%);\n"
"            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.35);\n"
"        }\n"
"        button:disabled {\n"
"            opacity: 0.55;\n"
"            cursor: not-allowed;\n"
"            box-shadow: none;\n"
"        }\n"
"        .status {\n"
"            min-height: 20px;\n"
"            font-size: 14px;\n"
"            color: var(--label-color);\n"
"        }\n"
"        .status.error {\n"
"            color: var(--input-error);\n"
"        }\n"
"        .hidden {\n"
"            display: none;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <main class=\"container\">\n"
"        <h1>Configure Access Point</h1>\n"
"        <form id=\"ap-form\" autocomplete=\"off\">\n"
"            <div class=\"form-field\">\n"
"                <label for=\"ssid\">SSID</label>\n"
"                <input id=\"ssid\" name=\"ssid\" type=\"text\" maxlength=\"32\" placeholder=\"Enter network name\" required>\n"
"            </div>\n"
"            <div class=\"form-field\">\n"
"                <label for=\"password\">Password</label>\n"
"                <input id=\"password\" name=\"password\" type=\"password\" maxlength=\"63\" placeholder=\"Minimum 8 characters\" required>\n"
"            </div>\n"
"            <div id=\"status\" class=\"status\"></div>\n"
"            <div class=\"actions\">\n"
"                <button type=\"submit\" id=\"ok-button\">Save</button>\n"
"                <button type=\"button\" id=\"cancel-button\" class=\"hidden\">Cancel</button>\n"
"            </div>\n"
"        </form>\n"
"    </main>\n"
"    <script>\n"
"        const form = document.getElementById('ap-form');\n"
"        const ssidInput = document.getElementById('ssid');\n"
"        const passwordInput = document.getElementById('password');\n"
"        const statusLabel = document.getElementById('status');\n"
"        const cancelButton = document.getElementById('cancel-button');\n"
"
"        const clearErrors = () => {\n"
"            ssidInput.classList.remove('error');\n"
"            passwordInput.classList.remove('error');\n"
"        };\n"
"
"        const setStatus = (message, isError = false) => {\n"
"            statusLabel.textContent = message || '';\n"
"            statusLabel.classList.toggle('error', isError);\n"
"        };\n"
"
"        const toggleCancel = (visible) => {\n"
"            if (visible) {\n"
"                cancelButton.classList.remove('hidden');\n"
"                cancelButton.disabled = false;\n"
"            } else {\n"
"                cancelButton.classList.add('hidden');\n"
"                cancelButton.disabled = true;\n"
"            }\n"
"        };\n"
"
"        const loadConfig = async () => {\n"
"            try {\n"
"                const response = await fetch('/api/v1/ap/config');\n"
"                if (!response.ok) {\n"
"                    throw new Error('Unable to read current configuration');\n"
"                }\n"
"                const data = await response.json();\n"
"                ssidInput.value = data.ssid || '';\n"
"                passwordInput.value = data.password || '';\n"
"                toggleCancel(Boolean(data.hasValidPassword));\n"
"                setStatus('');\n"
"            } catch (error) {\n"
"                setStatus(error.message, true);\n"
"                toggleCancel(false);\n"
"            }\n"
"        };\n"
"
"        form.addEventListener('submit', async (event) => {\n"
"            event.preventDefault();\n"
"            clearErrors();\n"
"            setStatus('Saving...');\n"
"
"            const ssid = ssidInput.value.trim();\n"
"            const password = passwordInput.value.trim();\n"
"
"            try {\n"
"                const body = new URLSearchParams({ ssid, password });\n"
"                const response = await fetch('/api/v1/ap/config', {\n"
"                    method: 'POST',\n"
"                    headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },\n"
"                    body: body.toString(),\n"
"                });\n"
"
"                const payload = await response.json();\n"
"                if (!response.ok || payload.status !== 'ok') {\n"
"                    if (payload.field === 'ssid') {\n"
"                        ssidInput.classList.add('error');\n"
"                    }\n"
"                    if (payload.field === 'password') {\n"
"                        passwordInput.classList.add('error');\n"
"                    }\n"
"                    throw new Error(payload.message || 'Failed to save configuration');\n"
"                }\n"
"
"                window.location.href = '/api/v1/main/';\n"
"            } catch (error) {\n"
"                setStatus(error.message, true);\n"
"                toggleCancel(false);\n"
"            }\n"
"        });\n"
"
"        cancelButton.addEventListener('click', () => {\n"
"            window.location.href = '/api/v1/main/';\n"
"        });\n"
"
"        ssidInput.addEventListener('input', () => ssidInput.classList.remove('error'));\n"
"        passwordInput.addEventListener('input', () => passwordInput.classList.remove('error'));\n"
"
"        loadConfig();\n"
"    </script>\n"
"</body>\n"
"</html>\n";

const char *http_service_page_ap_html(void)
{
    return PAGE_AP_HTML;
}
