/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tapgate_MsgHeader, tapgate_MsgHeader, AUTO)


PB_BIND(tapgate_MsgAction, tapgate_MsgAction, 2)


PB_BIND(tapgate_MsgStatus, tapgate_MsgStatus, AUTO)



