/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tapgate_MessageOnWire, tapgate_MessageOnWire, 2)


PB_BIND(tapgate_EnrollMessage, tapgate_EnrollMessage, AUTO)


PB_BIND(tapgate_RegularMessage, tapgate_RegularMessage, 2)


PB_BIND(tapgate_MessageEncryptedPayload, tapgate_MessageEncryptedPayload, 2)


PB_BIND(tapgate_MessageDoAction, tapgate_MessageDoAction, AUTO)



